version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: syncal_database  # Replace with your database name
      POSTGRES_USER: admin    # Replace with your database user
      POSTGRES_PASSWORD: s9HMY8]dgF0!Wpxa  # Replace with your database password

  web:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile  # Specify the path to your Dockerfile
    command: python manage.py runserver 0.0.0.0:8090
    volumes:
      - ./:/app  # Map your Django project directory to /app in the container
    ports:
      - "8090:8090"  # Use the same port for the host and container
    depends_on:
      - db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
