# Generated by Django 4.2.5 on 2023-10-05 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='YourDefaultName', max_length=100)),
                ('description', models.TextField(default='Custom Calendar')),
                ('start', models.DateTimeField(auto_now=True)),
                ('end', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Default Event Name', max_length=100)),
                ('description', models.TextField(default='Default Event Desc.')),
                ('start', models.DateTimeField()),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Default Event Name', max_length=100)),
                ('description', models.TextField(default='Default Event Desc.')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('color', models.CharField(default='bg-red-200 text-red-500', max_length=100)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('calendar_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_core.calendar')),
            ],
        ),
    ]
