# Generated by Django 4.2.6 on 2023-10-20 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='YourDefaultName', max_length=100)),
                ('description', models.TextField(default='Custom Calcreatedar')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='YourDefaultName', max_length=100)),
                ('description', models.TextField(default='Custom Calcreatedar')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('book_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor_core.book')),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='YourDefaultName', max_length=100)),
                ('description', models.TextField(default='Custom Calcreatedar')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='YourDefaultName', max_length=100)),
                ('description', models.TextField(default='Custom Calcreatedar')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('chapter_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor_core.chapter')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='shelf_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor_core.shelf'),
        ),
        migrations.AddField(
            model_name='book',
            name='user_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
