# Generated by Django 4.2.6 on 2023-10-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
