# Generated by Django 4.2.6 on 2023-10-21 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor_core', '0003_rename_is_favorite_page_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='users',
            field=models.ManyToManyField(default=1, to=settings.AUTH_USER_MODEL),
        ),
    ]
