# Generated by Django 4.2.6 on 2023-10-21 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor_core', '0004_page_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='users',
        ),
    ]
